version: 2

builds:
  - main: ./cmd/server
    binary: wsapi
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - "docker.io/wsapichat/wsapi:{{ .Tag }}"
      - "docker.io/wsapichat/wsapi:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.source=https://github.com/wsapi-chat/wsapi-app"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
      - "--label=org.opencontainers.image.licenses=MIT"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
      - "^chore:"
